# this workflow will build a dist folder with vite. 

name: Build production files

on: 
  push: 
    branches: 
      - deploy
  workflow_dispatch:

jobs: 
  build: 
    name: Build dist
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload Prod-ready files
        uses: actions/upload-artifact@v3
        with: 
          name: github-pages
          path: ./dist
  deploy: 
      name: Deploy files to gh-pages branch
      needs: build
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
          with:
            ref: gh-pages

        - name: Download Dist from artifacts
          uses: actions/download-artifact@v3
          with: 
            name: github-pages
            path: ./dist
